# Generated by Django 4.2.16 on 2024-11-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aimgamescore_profile_typinggamescore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typinggamescore',
            name='score',
            field=models.FloatField(),
        ),
    ]
